// springapp-angular/src/app/componentes/publica/ficha/ficha.component.ts
import { Component, Input } from '@angular/core';
import { Producto } from '../../../modelos/producto';
import { BotonComponent } from "../../biblioteca/boton/boton.component";
import { CurrencyPipe } from '@angular/common';

@Component({
  selector: 'app-ficha',
  imports: [BotonComponent, CurrencyPipe],
  templateUrl: './ficha.component.html',
  styleUrl: './ficha.component.css'
})
export class FichaComponent {
  @Input() horizontal = false;

  @Input() producto: Producto = {
    id: 5,
    nombre: 'Producto de prueba',
    precio: 1234.56,
    descripcion: 'Descripción de prueba',
    categoria: {
      id: 2,
      nombre: 'Categoría de prueba',
      descripcion: 'Descripción de la categoría'
    }
  };
}

@if(!horizontal) {
<div class="card h-100">
    <img src="https://picsum.photos/400/300" class="card-img-top" alt="">
    <div class="card-body">
        <h5 class="card-title">{{producto.nombre}}</h5>
        <p class="card-text">
            <jl-boton enlace="/detalle" etiqueta="Ver detalle"/>
        </p>
    </div>
    <div class="card-footer">
        <small class="text-body-secondary">{{producto.precio | currency: 'EUR': 'symbol' : '1.2-2' : 'es'}}</small>
    </div>
</div>
}

@if(horizontal) {
<div class="card mb-3">
    <div class="row g-0">
        <div class="col-md-4">
            <img src="https://picsum.photos/400/500" class="img-fluid rounded-start" alt="...">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title">{{producto.nombre}}</h5>
                <p class="card-text">{{producto.descripcion}}</p>
                <p>{{producto.categoria.nombre}}</p>
                <div class="card-text">
                    <jl-boton enlace="/carrito" etiqueta="Añadir al carrito"/>
                </div>
                <p class="card-text">
                    <small class="text-body-secondary">{{producto.precio | currency: 'EUR': 'symbol' : '1.2-2' : 'es'}}</small>
                </p>
            </div>
        </div>
    </div>
</div>
}

// FRONTEND/REACT/crud/src/componentes/Ficha.js
export default function Ficha() {
    return (
        <div className="col">
            <div className="card h-100">
                <img src="https://picsum.photos/400/300?producto.id" className="card-img-top" alt="..." />
                <div className="card-body">
                    <h5 className="card-title">producto.nombre</h5>
                    <p className="card-text">producto.descripcion</p>
                </div>
                <div className="card-footer">
                    <small className="text-body-secondary">producto.precio</small>
                </div>
            </div>
        </div>
    );
}
