// FRONTEND/REACT/crud/src/componentes/Ficha.js
export default function Ficha() {
    return (
        <div className="col">
            <div className="card h-100">
                <img src="https://picsum.photos/400/300?producto.id" className="card-img-top" alt="..." />
                <div className="card-body">
                    <h5 className="card-title">producto.nombre</h5>
                    <p className="card-text">producto.descripcion</p>
                </div>
                <div className="card-footer">
                    <small className="text-body-secondary">producto.precio</small>
                </div>
            </div>
        </div>
    );
}

// springapp-angular/src/app/componentes/ficha/ficha.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-ficha',
  imports: [],
  templateUrl: './ficha.component.html',
  styleUrl: './ficha.component.css'
})
export class FichaComponent {

}

<div class="col">
    <div class="card h-100">
        <img src="https://picsum.photos/400/300" class="card-img-top" alt="">
        <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">
                <a class="btn btn-primary">Ver detalle</a>
            </p>
        </div>
        <div class="card-footer">
            <small class="text-body-secondary">Last updated 3 mins ago</small>
        </div>
    </div>
</div>
